name: Deploy Snapshot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: maven
          server-id: 'ossrh'
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-passphrase: SIGN_KEY_PASS
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Test
        run: mvn -B package --file pom.xml

      - name: install Snapshot for Artifact Test
        run: |
          mvn -B package --no-transfer-progress -DskipTests --file jfr4jdbc-driver/pom.xml
          mvn -B --no-transfer-progress install:install-file -Dfile=target/jfr4jdbc-driver-999-SNAPSHOT.jar -DgroupId=dev.jfr4jdbc -DartifactId=jfr4jdbc-driver -Dversion=999-SNAPSHOT -Dpackaging=jar --file jfr4jdbc-driver/pom.xml

      - name: Artifact Test
        run: mvn -B test --file artifact-test/pom.xml

      - name: Deploy Snapshot
        env:
          OSSRH_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.MAVEN_USER_PASSWORD }}
          SIGN_KEY_PASS: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: mvn -B deploy --no-transfer-progress -DskipTests --file jfr4jdbc-driver/pom.xml